# Generated by Django 2.0 on 2017-12-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='ne_valuation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='ng_valuation',
            field=models.FloatField(null=True),
        ),
    ]
