# Generated by Django 2.0 on 2017-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0003_auto_20171222_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='log',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
