# Generated by Django 2.0 on 2017-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0004_auto_20171222_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
