# Generated by Django 2.0 on 2017-12-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0005_auto_20171222_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='deactivated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseprice',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='home2.House'),
        ),
    ]
