# Generated by Django 2.0 on 2017-12-23 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0006_auto_20171223_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseprice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
