# Generated by Django 2.0 on 2017-12-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0008_house_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='freehold',
        ),
    ]
