# Generated by Django 2.0 on 2018-01-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0010_house_called_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='called_on',
            new_name='first_call_on',
        ),
    ]
