# Generated by Django 2.0 on 2018-01-07 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0011_auto_20180102_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='first_visit_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseoffer',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='home2.House'),
        ),
        migrations.AlterUniqueTogether(
            name='houseoffer',
            unique_together={('house', 'date')},
        ),
    ]
